import { Brain, Mic, BarChart3 } from "lucide-react";
import { motion } from "framer-motion";

const Features = () => {
  return (
    <section id="features" className="py-24 bg-white dark:bg-emerald-950">

      <h2 className="text-center text-3xl font-bold text-gray-900 dark:text-white mb-16">
        Powerful AI Interview Features
      </h2>

      <div className="grid md:grid-cols-3 gap-12 px-20">

        {/* Feature 1 */}
        <motion.div
          initial={{ opacity: 0, y: 40 }}
          whileInView={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6 }}
          className="group p-8 backdrop-blur-lg bg-white/70 dark:bg-emerald-900/40 border border-white/20 shadow-xl rounded-2xl text-center transition-all duration-300 hover:-translate-y-3 hover:shadow-emerald-500/20 hover:shadow-2xl"
        >
          <Brain
            className="mx-auto text-emerald-600 transition-transform duration-300 group-hover:scale-110"
            size={40}
          />

          <h3 className="mt-4 font-semibold text-xl text-gray-800 dark:text-gray-200">
            AI Questions
          </h3>

          <p className="text-gray-500 dark:text-gray-300 mt-2">
            Smart interview questions generated by AI.
          </p>
        </motion.div>


        {/* Feature 2 */}
        <motion.div
          initial={{ opacity: 0, y: 40 }}
          whileInView={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6, delay: 0.2 }}
          className="group p-8 backdrop-blur-lg bg-white/70 dark:bg-emerald-900/40 border border-white/20 shadow-xl rounded-2xl text-center transition-all duration-300 hover:-translate-y-3 hover:shadow-emerald-500/20 hover:shadow-2xl"
        >
          <Mic
            className="mx-auto text-emerald-600 transition-transform duration-300 group-hover:scale-110"
            size={40}
          />

          <h3 className="mt-4 font-semibold text-xl text-gray-800 dark:text-gray-200">
            Voice Interviews
          </h3>

          <p className="text-gray-500 dark:text-gray-300 mt-2">
            Practice answering questions using voice.
          </p>
        </motion.div>


        {/* Feature 3 */}
        <motion.div
          initial={{ opacity: 0, y: 40 }}
          whileInView={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6, delay: 0.4 }}
          className="group p-8 backdrop-blur-lg bg-white/70 dark:bg-emerald-900/40 border border-white/20 shadow-xl rounded-2xl text-center transition-all duration-300 hover:-translate-y-3 hover:shadow-emerald-500/20 hover:shadow-2xl"
        >
          <BarChart3
            className="mx-auto text-emerald-600 transition-transform duration-300 group-hover:scale-110"
            size={40}
          />

          <h3 className="mt-4 font-semibold text-xl text-gray-800 dark:text-gray-200">
            Analytics
          </h3>

          <p className="text-gray-500 dark:text-gray-300 mt-2">
            Track performance with AI evaluation.
          </p>
        </motion.div>

      </div>

    </section>
  );
};

export default Features;